### ISSUE TITLE
Feature request: remove Numpy dependency

### ISSUE THREAD

**Issue by martinbrose** [tevslin/cloudflarepycli#13]
I'd like to propose to remove the dependency on the Numpy package.

### Reason
I'm using ```cloudflarepycli``` as part of docker containers that I use for a selection of OS flavors, e.g. linux/arm/v7 and linux/arm/v6. Numpy doesn't seem to be available for these platforms and as a result, a wheel is being built during the docker build process. This is very time-consuming and actually increases the resulting docker image size significantly, from 90MB to 160MB.

**Comment by tevslin** [comment]
Martin,

Is scipy available for these platforms? I'd rather avoid the extra code and extra processing if possible.

Thank you
