### ISSUE TITLE
Version 1.8.1 on PyPI

### ISSUE THREAD

**Issue by martinbrose** [tevslin/cloudflarepycli#16]
Hi @tevslin,

when will version 1.8.1 be available on PyPI?

Please let me know if I can help with anything.

Best regards,
Martin

**Comment by tevslin** [comment]
Hi Martin,

 

Thanks for reminding me. I do hope to get this done in the next few days.

 

Tom

 

From: Martin Brose ***@***.***> 
Sent: Sunday, September 17, 2023 4:59 AM
To: tevslin/cloudflarepycli ***@***.***>
Cc: Tom Evslin ***@***.***>; Mention ***@***.***>
Subject: [tevslin/cloudflarepycli] Version 1.8.1 on PyPI (Issue #16)

 

Hi @tevslin <https://github.com/tevslin> ,

when will version 1.8.1 be available on PyPI?

Please let me know if I can help with anything.

Best regards,
Martin

**Comment by martinbrose** [comment]
Many thanks @tevslin!

The Docker build process was so much faster now and the resulting image much smaller.
Thanks again for considering my other pull requests!

Have a great weekend!

**Comment by tevslin** [comment]
You’re welcome, Martin.
