### ISSUE TITLE
Feature Request: Add 100MB Download Tests to Match Cloudflare Web Test

### ISSUE THREAD

**Issue by dreondre** [tevslin/cloudflarepycli#17]
Hi there,

Would it be possible to add a 100 MB test to match that of the Cloudflare speed test?
Currently the website shows 100 kB, 1 MB, 10 MB, 25 MB and 100 MB.
However, the latest version of cloudflarepycli only has the first 4.

**Comment by tevslin** [comment]
Hi,

I left this out because, in many instance, it induces too much latency affecting whatever else is going on locally.  However, the actual tests run can be modified via a parameter: thetester=cloudflareclass.cloudflare()

**Comment by dreondre** [comment]
I think so. I’m not really a developer and was looking to see this change downstream to another git repo that uses your code. 
That said, I’ll look at this as time permits and see what I can learn. 
Thanks!
